use lazy_static::lazy_static;
use regex::Regex;

use crate::{constants::NO_PIECE, game::{moves::move_parse::generate_move_vectors, representations::{drop::DropSet, piece::Piece, state::State, vector::Leg}}, leg, p_index, x, y};


lazy_static! {
    pub static ref DROP_PATTERN: Regex =
        Regex::new(r"^([kfcd]*)(.+)~(.+)@(?:(.+)~(.+))?$").unwrap();
}

/// the Cheesy Drop Notation (CDN) is as follows:
///
/// [modifiers][allower compound]~[pieces]@[stoppers compound]~[pieces]
///
/// The allower compound is a compound atomic in Cheesy King Notation (CKN).
/// All vectors generated by the allower are checked to see if [pieces] are
/// present on those squares. If they are, then the drop is legal.
///
/// The stoppers compound is also a compound atomic in CKN. All vectors
/// generated by the stoppers are checked to see if [pieces] are not present on
/// those squares. If they are, then the drop is illegal.
///
/// The modifiers are as follows:
/// - k : if set, this drop cannot deliver checkmate, otherwise, it can.
/// - f : if set, this drop can be used to drop to forbidden squares
/// - d : if set, this drop will remove every piece detected by the allowers
/// - c : if set, this drop will remove every piece detected by the stoppers
///
/// Pieces are the chars of the pieces that are relevant to the allowers and
/// stoppers. * means all pieces including no piece. ? means no piece.
pub fn generate_drop_vectors(piece: &Piece, state: &State) -> DropSet {

    let parts = piece.drop.split('|').collect::<Vec<&str>>();

    let mut drop_set = Vec::new();
    for part in parts {
        let captures = DROP_PATTERN
            .captures(part)
            .unwrap_or_else(|| panic!("Invalid drop format {}", piece.drop));

        #[cfg(debug_assertions)]
        println!(
            "[DEBUG] Captured groups for piece {}: {:?}",
            piece.name, captures
        );

        let mut move_result = p_index!(piece) as u32;

        let modifiers = captures.get(1).map_or("", |m| m.as_str());

        if modifiers.contains('k') {
            move_result |= 1 << 20;
        }

        if modifiers.contains('f') {
            move_result |= 1 << 21;
        }

        if modifiers.contains('d') {
            move_result |= 1 << 22;
        }

        if modifiers.contains('c') {
            move_result |= 1 << 23;
        }

        let (allowers, allower_pieces) =
        match (captures.get(2), captures.get(3)) {
            (Some(a), Some(p)) => (a.as_str(), p.as_str()),
            (None, None) => ("", ""),
            _ => panic!(
                concat!(
                    "Invalid drop format for piece: {} ",
                    "allowers and allower_pieces must ",
                    "both be present or both absent"
                ),
                piece.name
            ),
        };
        let allowers_vecs = if allowers.is_empty() {
            Vec::new()
        } else {
            generate_move_vectors(allowers, state)
        };

        #[cfg(debug_assertions)]
        println!(
            "[DEBUG] Parsed drop for piece {}: \
            move_result = {}, allowers = {:#?}",
            piece.name, move_result, allowers_vecs
        );

        let allower_result = allowers_vecs.iter().flat_map(
            |multi_leg_vector| {
                let leg = leg!(multi_leg_vector[0]);

                let x = x!(leg) as u32 & 0xFF;
                let y = y!(leg) as u32 & 0xFF;
                allower_pieces.chars().map(|piece_char| {
                    let piece_index =
                        if piece_char == '?' {NO_PIECE as u32}
                        else {state.piece_char_map[&piece_char] as u32};

                    (piece_index << 16) | (y << 8) | x
                }).collect::<Vec<u32>>()
            }
        ).collect::<Vec<u32>>();

        #[cfg(debug_assertions)]
        println!(
            "[DEBUG] Encoded allowers for piece {}: {:?}",
            piece.name, allower_result
        );

        let (stoppers, stopper_pieces) =
        match (captures.get(4), captures.get(5)) {
            (Some(s), Some(p)) => (s.as_str(), p.as_str()),
            (None, None) => ("", ""),
            _ => panic!(
                concat!(
                    "Invalid drop format for piece: {} ",
                    "stoppers and stopper_pieces must ",
                    "both be present or both absent"
                ),
                piece.name
            ),
        };
        let stoppers_vecs = if stoppers.is_empty() {
            Vec::new()
        } else {
            generate_move_vectors(stoppers, state)
        };

        #[cfg(debug_assertions)]
        println!(
            "[DEBUG] Parsed drop for piece {}: \
            move_result = {}, stoppers = {:#?}",
            piece.name, move_result, stoppers_vecs
        );

        let stopper_result = stoppers_vecs.iter().flat_map(
            |multi_leg_vector| {
                let leg = leg!(multi_leg_vector[0]);

                let x = x!(leg) as u32 & 0xFF;
                let y = y!(leg) as u32 & 0xFF;
                stopper_pieces.chars().map(|piece_char| {
                    let piece_index =
                        if piece_char == '?' {NO_PIECE as u32}
                        else {state.piece_char_map[&piece_char] as u32};

                    (piece_index << 16) | (y << 8) | x
                }).collect::<Vec<u32>>()
            }
        ).collect::<Vec<u32>>();

        #[cfg(debug_assertions)]
        println!(
            "[DEBUG] Encoded stoppers for piece {}: {:?}",
            piece.name, stopper_result
        );

        drop_set.push((move_result, allower_result, stopper_result));
    }

    drop_set
}