= general =
Embassy Chess
rnbqkcabnr/pppppppppp/10/10/10/10/PPPPPPPPPP/RNBQKCABNR w KQkq *

= rules =
castling
en passant
promotions

= termination =
repetition: 3 draw
counter: 100 Pp

= pieces =
Pp:Pawn
Rr:Rook
Nn:Knight
Bb:Bishop
Qq:Queen
Cc:Chancellor
Aa:Archbishop
Kk:King

= castling =
pieces:KRkr
K:10/10/10/10/10/10/10/4K***+R
Q:10/10/10/10/10/10/10/R***K5
k:4k***+r/10/10/10/10/10/10/10
q:r***k5/10/10/10/10/10/10/10
K:10/10/10/10/10/10/10/6RK2
Q:10/10/10/10/10/10/10/1KR7
k:6rk2/10/10/10/10/10/10/10
q:1kr7/10/10/10/10/10/10/10

= piece order =
PRNBQCAKprnbqcak

= piece roles =
royal       :Kk

= piece moves =
Pp:mnW|im<nW-pnW>|tcnF
Rr:R
Nn:N
Bb:B
Qq:Q
Cc:R|N
Aa:N|B
Kk:K

= promotions =
P:RNBQCA
p:rnbqca

= mandatory promotion zones =
P:XXXXXXXXXX/10/10/10/10/10/10/10
p:10/10/10/10/10/10/10/XXXXXXXXXX
