= general =
Ai-Wok
rnsaksnr/8/pppppppp/8/8/PPPPPPPP/8/RNSKASNR w

= rules =
promotions
repetition limit

= repetition limit =
limit:3

= pieces =
Pp:Pawn
Rr:Rook
Nn:Knight
Ss:Khon
Aa:Ai-Wok
Kk:King

= piece order =
PRNSAKprnsak

= piece roles =
royal       :Kk

= piece moves =
Pp:mnW|cnF
Rr:R
Nn:N
Ss:F|nW
Aa:R|N|F
Kk:K

= promotions =
P:A
p:a

= mandatory promotion zones =
P:8/8/XXXXXXXX/8/8/8/8/8
p:8/8/8/8/8/XXXXXXXX/8/8
