title="Capablanca Chess"
initial_position="ranbqkbncr/pppppppppp/10/10/10/10/PPPPPPPPPP/RANBQKBNCR w KQkq -"
files=10
ranks=8

[special_rules]
promotions=true

[[pieces]]
name="Pawn"
charset="Pp"
movement="mnW|im<nW-pnW>|tcnF"
value=1000
big=false
major=false
royal=false

[[pieces]]
name="Rook"
charset="Rr"
movement="R"
value=5000
big=true
major=true
royal=false

[[pieces]]
name="Knight"
charset="Nn"
movement="N"
value=3000
big=true
major=false
royal=false

[[pieces]]
name="Bishop"
charset="Bb"
movement="B"
value=3375
big=true
major=false
royal=false

[[pieces]]
name="Queen"
charset="Qq"
movement="Q"
value=9000
big=true
major=true
royal=false

[[pieces]]
name="Archbishop"
charset="Aa"
movement="B|N"
value=8500
big=true
major=true
royal=false

[[pieces]]
name="Chancellor"
charset="Cc"
movement="R|N"
value=8500
big=true
major=true
royal=false

[[pieces]]
name="King"
charset="K_"
movement="K|O{5}{2}|o{4}{1}"
value=inf
big=true
major=false
royal=true

[[pieces]]
name="King"
charset="_k"
movement="K|o{5}{2}|O{4}{1}"
value=inf
big=true
major=false
royal=true

[promotions]
P="RNBQAC"
p="rbnqac"

[promotion_zones_mandatory]
P="XXXXXXXXXX/10/10/10/10/10/10/10"
p="10/10/10/10/10/10/10/XXXXXXXXXX"

[initial_setup]
K="10/10/10/10/10/10/10/5X4"
k="5X4/10/10/10/10/10/10/10"
P="10/10/10/10/10/10/XXXXXXXXXX/10"
p="10/XXXXXXXXXX/10/10/10/10/10/10"
R="10/10/10/10/10/10/10/X8X"
r="X8X/10/10/10/10/10/10/10"
