[general]
Capablanca Chess
ranbqkbncr/pppppppppp/10/10/10/10/PPPPPPPPPP/RANBQKBNCR w KQkq *

[rules]
castling
en passant
promotions

[pieces]
Pp:Pawn
Rr:Rook
Nn:Knight
Bb:Bishop
Qq:Queen
Aa:Archbishop
Cc:Chancellor
Kk:King

[piece values]
Pp:1000
Rr:5000
Nn:3000
Bb:3375
Qq:8875
Aa:7500
Cc:7500
Kk:4000

[piece roles]
big         :RrNnBbQqAaCc
major       :RrQqAaCc
royal       :Kk

[piece moves]
Pp:mnW|im<nW-pnW>|tcnF
Rr:R
Nn:N
Bb:B
Qq:Q
Aa:N|B
Cc:R|N
K:K|O{5,2}|o{4,1}
k:K|o{5,2}|O{4,1}

[promotions]
P:RNBQAC
p:rnbqac

[mandatory promotion zones]
P:XXXXXXXXXX/10/10/10/10/10/10/10
p:10/10/10/10/10/10/10/XXXXXXXXXX