= general =
Capablanca Chess
ranbqkbncr/pppppppppp/10/10/10/10/PPPPPPPPPP/RANBQKBNCR w KQkq *

= rules =
castling
en passant
promotions
halfmove clock
repetition limit

= repetition limit =
limit:3

= halfmove clock =
limit:100
pieces:Pp

= pieces =
Pp:Pawn
Rr:Rook
Nn:Knight
Bb:Bishop
Qq:Queen
Aa:Archbishop
Cc:Chancellor
Kk:King

= piece order =
PRNBQACKprnbqack

= piece roles =
royal       :Kk

= piece moves =
Pp:mnW|im<nW-pnW>|tcnF
Rr:R
Nn:N
Bb:B
Qq:Q
Aa:N|B
Cc:R|N
Kk:K

= castling =
pieces:KRkr
K:10/10/10/10/10/10/10/5K***R
Q:10/10/10/10/10/10/10/R+***K4
k:5k***r/10/10/10/10/10/10/10
q:r+***k4/10/10/10/10/10/10/10
K:10/10/10/10/10/10/10/7RK1
Q:10/10/10/10/10/10/10/2KR6
k:7rk1/10/10/10/10/10/10/10
q:2kr6/10/10/10/10/10/10/10

= promotions =
P:RNBQAC
p:rnbqac

= mandatory promotion zones =
P:XXXXXXXXXX/10/10/10/10/10/10/10
p:10/10/10/10/10/10/10/XXXXXXXXXX
