= general =
Chancellor Chess
rnbqkcnbr/ppppppppp/9/9/9/9/9/PPPPPPPPP/RNBQKCNBR w KQkq *

= rules =
castling
en passant
promotions
halfmove clock
repetition limit

= pieces =
Pp:Pawn
Rr:Rook
Nn:Knight
Bb:Bishop
Qq:Queen
Cc:Chancellor
Kk:King

= castling =
pieces:KRkr
K:9/9/9/9/9/9/9/9/4K**+R
Q:9/9/9/9/9/9/9/9/R+**K4
k:4k**+r/9/9/9/9/9/9/9/9
q:r+**k4/9/9/9/9/9/9/9/9
K:9/9/9/9/9/9/9/9/5RK2
Q:9/9/9/9/9/9/9/9/2KR5
k:5rk2/9/9/9/9/9/9/9/9
q:2kr5/9/9/9/9/9/9/9/9

= repetition limit =
limit:3

= halfmove clock =
limit:100
pieces:Pp

= piece order =
PRNBQCKprnbqck

= piece roles =
royal       :Kk

= piece moves =
Pp:mnW|im<nW-pnW>|tcnF
Rr:R
Nn:N
Bb:B
Qq:Q
Cc:R|N
Kk:K

= promotions =
P:RNBQC
p:rnbqc

= mandatory promotion zones =
P:XXXXXXXXX/9/9/9/9/9/9/9/9
p:9/9/9/9/9/9/9/9/XXXXXXXXX
