= general =
Crazyhouse
rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq * -/-

= rules =
castling
en passant
promotions
drops
forbidden zones

= pieces =
Pp:Pawn
Rr:Rook
Nn:Knight
Bb:Bishop
Qq:Queen
Kk:King

= piece order =
PRNBQKprnbqk

= piece roles =
royal       :Kk

= piece moves =
Pp:mv!vnW|im<nW-pnW>|tcv!vnF
Rr:R
Nn:N
Bb:B
Qq:Q
K:K
k:K

= castling =
pieces:KRkr
K:8/8/8/8/8/8/8/4K**R
Q:8/8/8/8/8/8/8/R+**K3
k:4k**r/8/8/8/8/8/8/8
q:r+**k3/8/8/8/8/8/8/8
K:8/8/8/8/8/8/8/5RK1
Q:8/8/8/8/8/8/8/2KR5
k:5rk1/8/8/8/8/8/8/8
q:2kr5/8/8/8/8/8/8/8

= promotions =
P:RNBQ
p:rnbq

= mandatory promotion zones =
P:XXXXXXXX/8/8/8/8/8/8/8
p:8/8/8/8/8/8/8/XXXXXXXX

= forbidden zones =
P:XXXXXXXX/8/8/8/8/8/8/XXXXXXXX
p:XXXXXXXX/8/8/8/8/8/8/XXXXXXXX
