= general =
EuroShogi
1nbgkgn1/1r4b1/pppppppp/8/8/PPPPPPPP/1B4R1/1NGKGBN1 w -/-

= rules =
promotions
drops
forbidden zones
stalemate loss
repetition limit

= repetition limit =
limit:4

= pieces =
Pp:Pawn
Nn:Knight
Gg:Gold
Kk:King
Rr:Rook
Bb:Bishop
Tt:Promoted Pawn
Vv:Promoted Knight
Dd:Dragon King
Hh:Dragon Horse

= piece order =
PNGKRBTVDHpngkrbtvdh

= piece roles =
royal       :Kk

= piece moves =
Pp:mnW|cnF
Nn:[1278]N
Gg:[..$46]K
Kk:K
Rr:R
Bb:B
Tt:[..$46]K
Vv:[..$46]K
Dd:R|F
Hh:B|W

= promotions =
P:T
N:V
R:D
B:H
p:t
n:v
r:d
b:h

= demotions =
T:P
V:N
D:R
H:B
t:p
v:n
d:r
h:b

= mandatory promotion zones =
// TODO verify EuroShogi promotion zone (last two ranks assumed).
P:XXXXXXXX/8/8/8/8/8/8/8
p:8/8/8/8/8/8/8/XXXXXXXX
N:XXXXXXXX/XXXXXXXX/8/8/8/8/8/8
n:8/8/8/8/8/8/XXXXXXXX/XXXXXXXX

= optional promotion zones =
P:XXXXXXXX/XXXXXXXX/8/8/8/8/8/8
p:8/8/8/8/8/8/XXXXXXXX/XXXXXXXX
N:XXXXXXXX/XXXXXXXX/8/8/8/8/8/8
n:8/8/8/8/8/8/XXXXXXXX/XXXXXXXX
R:XXXXXXXX/XXXXXXXX/8/8/8/8/8/8
r:8/8/8/8/8/8/XXXXXXXX/XXXXXXXX
B:XXXXXXXX/XXXXXXXX/8/8/8/8/8/8
b:8/8/8/8/8/8/XXXXXXXX/XXXXXXXX

= drop rules =
P:k@#~?@n+sW*~P
p:k@#~?@n+sW*~p

= forbidden zones =
P:XXXXXXXX/8/8/8/8/8/8/8
p:8/8/8/8/8/8/8/XXXXXXXX
N:XXXXXXXX/XXXXXXXX/8/8/8/8/8/8
n:8/8/8/8/8/8/XXXXXXXX/XXXXXXXX
