= general =
Chess
rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq *

= rules =
castling
en passant
promotions

= pieces =
Pp:Pawn
Rr:Rook
Nn:Knight
Bb:Bishop
Qq:Queen
Kk:King

= piece values =
Pp:1000
Rr:5000
Nn:3000
Bb:3375
Qq:8875
Kk:4000

= piece roles =
big         :RrNnBbQq
major       :RrQq
royal       :Kk

= piece moves =
Pp:mnW|im<nW-pnW>|tcnF
Rr:R
Nn:N
Bb:B
Qq:Q
K:K|O{4,2}|o{3,1}
k:K|o{4,2}|O{3,1}

= promotions =
P:RNBQ
p:rnbq

= mandatory promotion zones =
P:XXXXXXXX/8/8/8/8/8/8/8
p:8/8/8/8/8/8/8/XXXXXXXX