= general =
Grand Chess
r8r/1nbqkcabn1/pppppppppp/10/10/10/10/PPPPPPPPPP/1NBQKCABN1/R8R w * -/-

= rules =
en passant
promotions
promote to captured

= pieces =
Pp:Pawn
Rr:Rook
Nn:Knight
Bb:Bishop
Qq:Queen
Aa:Archbishop
Cc:Chancellor
Kk:King

= piece values =
Pp:1000
Rr:5000
Nn:3000
Bb:3375
Qq:8875
Aa:7500
Cc:7500
Kk:4000

= piece roles =
big         :RrNnBbQqAaCc
major       :RrQqAaCc
royal       :Kk

= piece moves =
Pp:mnW|im<nW-pnW>|tcnF
Rr:R
Nn:N
Bb:B
Qq:Q
Aa:N|B
Cc:R|N
K:K
k:K

= promotions =
P:RNBQAC
p:rnbqac

= mandatory promotion zones =
P:XXXXXXXXXX/10/10/10/10/10/10/10/10/10
p:10/10/10/10/10/10/10/10/10/XXXXXXXXXX

= optional promotion zones =
P:XXXXXXXXXX/XXXXXXXXXX/XXXXXXXXXX/10/10/10/10/10/10/10
p:10/10/10/10/10/10/10/XXXXXXXXXX/XXXXXXXXXX/XXXXXXXXXX