title="Grand Chess"
initial_position="r8r/1nbqkcabn1/pppppppppp/10/10/10/10/PPPPPPPPPP/1NBQKCABN1/R8R w -"
files=10
ranks=10

[special_rules]
en_passant=true
promotions=true
promote_to_captured=true

[[pieces]]
name="Pawn"
charset="Pp"
movement="mnW|im<nW-pnW>|tcnF"
value=1000
big=false
major=false
royal=false

[[pieces]]
name="Rook"
charset="Rr"
movement="R"
value=5000
big=true
major=true
royal=false

[[pieces]]
name="Knight"
charset="Nn"
movement="N"
value=3000
big=true
major=false
royal=false

[[pieces]]
name="Bishop"
charset="Bb"
movement="B"
value=3375
big=true
major=false
royal=false

[[pieces]]
name="Queen"
charset="Qq"
movement="Q"
value=9000
big=true
major=true
royal=false

[[pieces]]
name="Archbishop"
charset="Aa"
movement="B|N"
value=8500
big=true
major=true
royal=false

[[pieces]]
name="Chancellor"
charset="Cc"
movement="R|N"
value=8500
big=true
major=true
royal=false

[[pieces]]
name="King"
charset="Kk"
movement="K"
value=inf
big=true
major=false
royal=true

[promotions]
P="RNBQAC"
p="rbnqac"

[promotion_zones_mandatory]
P="XXXXXXXXXX/10/10/10/10/10/10/10/10/10"
p="10/10/10/10/10/10/10/10/10/XXXXXXXXXX"

[promotion_zones_optional]
P="XXXXXXXXXX/XXXXXXXXXX/XXXXXXXXXX/10/10/10/10/10/10/10"
p="10/10/10/10/10/10/10/XXXXXXXXXX/XXXXXXXXXX/XXXXXXXXXX"

[initial_setup]
P="10/10/10/10/10/10/10/XXXXXXXXXX/10/10"
p="10/10/XXXXXXXXXX/10/10/10/10/10/10/10"
