= general =
Hoppel-Poppel
rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq *

= rules =
castling
en passant
promotions
halfmove clock
repetition limit

= pieces =
Pp:Pawn
Rr:Rook
Nn:Knight
Bb:Bishop
Qq:Queen
Kk:King

= castling =
pieces:KRkr
K:8/8/8/8/8/8/8/4K**R
Q:8/8/8/8/8/8/8/R+**K3
k:4k**r/8/8/8/8/8/8/8
q:r+**k3/8/8/8/8/8/8/8
K:8/8/8/8/8/8/8/5RK1
Q:8/8/8/8/8/8/8/2KR5
k:5rk1/8/8/8/8/8/8/8
q:2kr5/8/8/8/8/8/8/8

= repetition limit =
limit:3

= halfmove clock =
limit:100
pieces:Pp

= piece order =
PRNBQKprnbqk

= piece roles =
royal       :Kk

= piece moves =
// Pawn: one forward, two on first move, diagonal capture, en passant.
Pp:mnW|im<nW-pnW>|tcnF
// Rook: slides orthogonally.
Rr:R
// Knight: moves as a Knight but CAPTURES as a Bishop.
// mN (move-only knight) | cB (capture-only bishop). TODO verify.
Nn:mN|cB
// Bishop: moves as a Bishop but CAPTURES as a Knight.
// mB (move-only bishop) | cN (capture-only knight). TODO verify.
Bb:mB|cN
// Queen: slides any direction.
Qq:Q
// King: one step any direction.
Kk:K

= promotions =
P:RNBQ
p:rnbq

= mandatory promotion zones =
P:XXXXXXXX/8/8/8/8/8/8/8
p:8/8/8/8/8/8/8/XXXXXXXX
