= general =
Janggi
r2a1a2r/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/R2A1A2R w 2H2EQ/2h2eq

= rules =
promotions
forbidden zones
setup phase
stand-offs

= pieces =
Pp:Soldier
Cc:Cannon
Rr:Chariot
Hh:Horse
Ee:Elephant
Aa:Advisor
Ff:Central Advisor
Kk:King
Qq:Central King

= piece values =
Pp:1000
Cc:5000
Rr:5000
Hh:3000
Ee:3375
Aa:1500
Ff:2000
Kk:2200
Qq:2500

= piece roles =
big         :CcRrHhEeAaFf
major       :CcRr
royal       :KkQq

= piece moves =
Pp:v!vn+e+wW|#-nF
Cc:cdg<v!vW-*>-uv!v#-mgc<v!vnW-*>|#-cdgB-u#-mgcnR
Rr:v!vW-*|#-B
Hh:W-nF
Ee:W-nF-.
Aa:W
Ff:K
Kk:W|#
Qq:K|#

= piece ranks =
1:PpRrHhEeAaFfKkQq

= promotions =
K:Q
k:q
Q:K
q:k
A:F
a:f
F:A
f:a

= mandatory promotion zones =
K:9/9/9/9/9/9/9/3X1X3/4X4/3X1X3
k:3X1X3/4X4/3X1X3/9/9/9/9/9/9/9
Q:9/9/9/9/9/9/9/4X4/3X1X3/4X4
q:4X4/3X1X3/4X4/9/9/9/9/9/9/9
A:9/9/9/9/9/9/9/3X1X3/4X4/3X1X3
a:3X1X3/4X4/3X1X3/9/9/9/9/9/9/9
F:9/9/9/9/9/9/9/4X4/3X1X3/4X4
f:4X4/3X1X3/4X4/9/9/9/9/9/9/9

= forbidden zones =
P:XXX1X1XXX/XXXX1XXXX/XXX1X1XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX1X1XXX/XXXX1XXXX/XXX1X1XXX
p:XXX1X1XXX/XXXX1XXXX/XXX1X1XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX1X1XXX/XXXX1XXXX/XXX1X1XXX
K:XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX3XXX/XXX3XXX/XXX3XXX
k:XXX3XXX/XXX3XXX/XXX3XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX
Q:XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX3XXX/XXX3XXX/XXX3XXX
q:XXX3XXX/XXX3XXX/XXX3XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX
A:XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX3XXX/XXX3XXX/XXX3XXX
a:XXX3XXX/XXX3XXX/XXX3XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX
F:XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX3XXX/XXX3XXX/XXX3XXX
f:XXX3XXX/XXX3XXX/XXX3XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX
R:XXX1X1XXX/XXXX1XXXX/XXX1X1XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX1X1XXX/XXXX1XXXX/XXX1X1XXX
r:XXX1X1XXX/XXXX1XXXX/XXX1X1XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX1X1XXX/XXXX1XXXX/XXX1X1XXX
C:XXX1X1XXX/XXXX1XXXX/XXX1X1XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX1X1XXX/XXXX1XXXX/XXX1X1XXX
c:XXX1X1XXX/XXXX1XXXX/XXX1X1XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX1X1XXX/XXXX1XXXX/XXX1X1XXX

= setup rules =
E:f@#-eW-wW~?-R-?@|f@#-eW-wW~?-?-F@|f@#-eW-wW~?-F-?@|f@#-eW-wW~?-?-R@
e:f@#-eW-wW~?-r-?@|f@#-eW-wW~?-?-f@|f@#-eW-wW~?-f-?@|f@#-eW-wW~?-?-r@
H:f@#-eW-wW~?-R-E@|f@#-eW-wW~?-E-F@|f@#-eW-wW~?-F-E@|f@#-eW-wW~?-E-R@
h:f@#-eW-wW~?-r-e@|f@#-eW-wW~?-e-f@|f@#-eW-wW~?-f-e@|f@#-eW-wW~?-e-r@
Qq:@#-sF~?-Ff@

= stand-off patterns =
Kk:nW{5}~KkQq@nW{..4}~*|nW{6}~KkQq@nW{..5}~*|nW{7}~KkQq@nW{..6}~*|nW{8}~KkQq@nW{..7}~*|nW{9}~KkQq@nW{..8}~*
Qq:nW{5}~KkQq@nW{..4}~*|nW{6}~KkQq@nW{..5}~*|nW{7}~KkQq@nW{..6}~*|nW{8}~KkQq@nW{..7}~*|nW{9}~KkQq@nW{..8}~*
