= general =
Janggi
r2a1a2r/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/R2A1A2R w 2H2EQ/2h2eq

= rules =
promotions
forbidden zones
setup phase

= pieces =
Pp:Soldier
Cc:Cannon
Rr:Chariot
Hh:Knight
Ee:Elephant
Aa:Advisor
Ff:Central Advisor
Kk:King
Qq:Central King

= piece values =
Pp:1000
Cc:5000
Rr:5000
Hh:3000
Ee:3375
Aa:1500
Ff:2000
Kk:2200
Qq:2500

= piece roles =
big         :CcRrHhEeAaFf
major       :CcRr
royal       :KkQq

= piece moves =
Pp:v!vn+e+wW|nF
Cc:cdg<v!vW-*>-vu!v#-mgc<v!vnW-*>|cdgB-u#-mgcnR
Rr:v!vW-*|Q
Hh:v!vW-v!vnF
Ee:v!vW-v!vnF-.
Aa:W
Ff:K
Kk:W|#|kc!k<v!vW-{5..9}>
Qq:K|#|kc!k<v!vW-{5..9}>

= piece ranks =
1:PpRrHhEeAaFfKkQq

= promotions =
K:Q
k:q
Q:K
q:k
A:F
a:f
F:A
f:a

= mandatory promotion zones =
K:9/9/9/9/9/9/9/3X1X3/4X4/3X1X3
k:3X1X3/4X4/3X1X3/9/9/9/9/9/9/9
Q:9/9/9/9/9/9/9/4X4/3X1X3/4X4
q:4X4/3X1X3/4X4/9/9/9/9/9/9/9
A:9/9/9/9/9/9/9/3X1X3/4X4/3X1X3
a:3X1X3/4X4/3X1X3/9/9/9/9/9/9/9
F:9/9/9/9/9/9/9/4X4/3X1X3/4X4
f:4X4/3X1X3/4X4/9/9/9/9/9/9/9

= forbidden zones =
P:XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX3XXX/XXX3XXX/XXX3XXX
p:XXX3XXX/XXX3XXX/XXX3XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX
K:XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX3XXX/XXX3XXX/XXX3XXX
k:XXX3XXX/XXX3XXX/XXX3XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX
Q:XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX3XXX/XXX3XXX/XXX3XXX
q:XXX3XXX/XXX3XXX/XXX3XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX
A:XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX3XXX/XXX3XXX/XXX3XXX
a:XXX3XXX/XXX3XXX/XXX3XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX
F:XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX3XXX/XXX3XXX/XXX3XXX
f:XXX3XXX/XXX3XXX/XXX3XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX
E:XXX3XXX/XXX3XXX/XXX3XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX
e:XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX3XXX/XXX3XXX/XXX3XXX
H:XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX3XXX/XXX3XXX/XXX3XXX
h:XXX3XXX/XXX3XXX/XXX3XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX
R:XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX3XXX/XXX3XXX/XXX3XXX
r:XXX3XXX/XXX3XXX/XXX3XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX
C:XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX3XXX/XXX3XXX/XXX3XXX
c:XXX3XXX/XXX3XXX/XXX3XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX

= setup rules =
E:f@#-eW-wW~?-R-?@|f@#-eW-wW~?-?-F@|f@#-eW-wW~?-F-?@|f@#-eW-wW~?-?-R@
e:f@#-eW-wW~?-r-?@|f@#-eW-wW~?-?-f@|f@#-eW-wW~?-f-?@|f@#-eW-wW~?-?-r@
H:f@#-eW-wW~?-R-E@|f@#-eW-wW~?-E-F@|f@#-eW-wW~?-F-E@|f@#-eW-wW~?-E-R@
h:f@#-eW-wW~?-r-e@|f@#-eW-wW~?-e-f@|f@#-eW-wW~?-f-e@|f@#-eW-wW~?-e-r@
Qq:@#-sF~?-Ff@