title="Los Alamos Chess"
initial_position="rnqknr/pppppp/6/6/PPPPPP/RNQKNR w"
files=6
ranks=6

[special_rules]
promotions=true

[[pieces]]
name="Pawn"
charset="Pp"
movement="mnW|cnF"
value=1000
big=false
major=false
royal=false

[[pieces]]
name="Rook"
charset="Rr"
movement="R"
value=5000
big=true
major=true
royal=false

[[pieces]]
name="Knight"
charset="Nn"
movement="N"
value=3000
big=true
major=false
royal=false

[[pieces]]
name="Queen"
charset="Qq"
movement="Q"
value=3000
big=true
major=true
royal=false

[[pieces]]
name="King"
charset="Kk"
movement="K"
value=inf
big=true
major=false
royal=true

[promotions]
P="RNQ"
p="rnq"

[promotion_zones_mandatory]
P="XXXXXX/6/6/6/6/6"
p="6/6/6/6/6/XXXXXX"
