[general]
Los Alamos Chess
rnqknr/pppppp/6/6/PPPPPP/RNQKNR w

[rules]
promotions

[pieces]
Pp:Pawn
Rr:Rook
Nn:Knight
Qq:Queen
Kk:King

[piece values]
Pp:1000
Rr:5000
Nn:3000
Qq:8875
Kk:4000

[piece roles]
big         :RrNnQq
major       :RrQq
royal       :Kk

[piece moves]
Pp:mnW|cnF
Rr:R
Nn:N
Qq:Q
Kk:K

[promotions]
P:RNQ
p:rnq

[mandatory promotion zones]
P:XXXXXX/6/6/6/6/6
p:6/6/6/6/6/XXXXXX