= general =
Mini Xianqi
rchkhcr/p1ppp1p/7/7/7/P1PPP1P/RCHKHCR w

= rules =
forbidden zones
stalemate loss

= pieces =
Pp:Pawn
Cc:Cannon
Rr:Chariot
Hh:Knight
Kk:General

= piece order =
PCRHKpcrhk

= evaluation parameters =
[2000, 5000, 5000, 3000, 2200]
[1, 1, 1, 1, 0]
[0, 1, 1, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

= piece roles =
royal       :Kk

= piece moves =
Pp:n+e+wW
Cc:cdR-u#-cnR|mR
Rr:R
Hh:W-nF
Kk:W|kc<v!vW-{2..6}>

= forbidden zones =
K:XXXXXXX/XXXXXXX/XXXXXXX/XXXXXXX/XX3XX/XX3XX/XX3XX
k:XX3XX/XX3XX/XX3XX/XXXXXXX/XXXXXXX/XXXXXXX/XXXXXXX