= general =
Mini Xianqi
rchkhcr/p1ppp1p/7/7/7/P1PPP1P/RCHKHCR w

= rules =
forbidden_zones

= pieces =
Pp:Pawn
Cc:Cannon
Rr:Chariot
Hh:Knight
Kk:General

= piece values =
Pp:2000
Cc:5000
Rr:5000
Hh:3000
Kk:2200

= piece roles =
big         :PpCcRrHhKk
major       :CcRr
royal       :Kk

= piece moves =
Pp:n+e+wW
Cc:cdR-u#-cnR|mR
Rr:R
Hh:W-nF
Kk:W|kc<v!vW-{2..6}>

= forbidden zones =
K:XXXXXXX/XXXXXXX/XXXXXXX/XXXXXXX/XX3XX/XX3XX/XX3XX
k:XX3XX/XX3XX/XX3XX/XXXXXXX/XXXXXXX/XXXXXXX/XXXXXXX