= general =
Mini Shogi
rbsgk/4p/5/P4/KGSBR w -/-

= rules =
promotions
drops
demote upon capture
forbidden zones
stalemate loss

= pieces =
Pp:Pawn
Ss:Silver
Gg:Gold
Kk:King
Rr:Rook
Bb:Bishop
Tt:Promoted Pawn
Ww:Promoted Silver
Dd:Dragon King
Hh:Dragon Horse

= piece values =
Pp:1000
Ss:3500
Gg:4000
Kk:5000
Rr:5000
Bb:3500
Tt:4000
Ww:4000
Dd:9000
Hh:8500

= piece roles =
big         :SsGgRrBbTtWwDdHh
major       :RrBb
royal       :Kk

= piece moves =
Pp:v!vnW
Ss:F|nW
Gg:[..$46]K
Kk:K
Rr:R
Bb:B
Tt:[..$46]K
Ww:[..$46]K
Dd:R|F
Hh:B|W

= promotions =
P:T
S:W
R:D
B:H
p:t
s:w
r:d
b:h

= mandatory promotion zones =
P:XXXXX/5/5/5/5
p:5/5/5/5/XXXXX

= optional promotion zones =
B:XXXXX/5/5/5/5
b:5/5/5/5/XXXXX
R:XXXXX/5/5/5/5
r:5/5/5/5/XXXXX
S:XXXXX/5/5/5/5
s:5/5/5/5/XXXXX

= drop rules =
P:k@#~?@n+sW*~P
p:k@#~?@n+sW*~p

= forbidden zones =
P:XXXXX/5/5/5/5
p:5/5/5/5/XXXXX