= general =
Shatranj
rnakfanr/pppppppp/8/8/8/8/PPPPPPPP/RNAKFANR w

= rules =
promotions
stalemate loss
repetition limit

= repetition limit =
limit:3

= pieces =
Pp:Soldier
Rr:Chariot
Nn:Horse
Aa:Alfil
Ff:Ferz
Kk:King

= piece order =
PRNAFKprnafk

= piece roles =
royal       :Kk

= piece moves =
Pp:mnW|cnF
Rr:R
Nn:N
Aa:A
Ff:F
Kk:K

= promotions =
P:F
p:f

= mandatory promotion zones =
P:XXXXXXXX/8/8/8/8/8/8/8
p:8/8/8/8/8/8/8/XXXXXXXX
