[general]
Shatranj
rnakfanr/pppppppp/8/8/8/8/PPPPPPPP/RNAKFANR w

[rules]
promotions

[pieces]
Pp:Soldier
Rr:Chariot
Nn:Horse
Aa:Alfil
Ff:Ferz
Kk:King

[piece values]
Pp:1000
Rr:5000
Nn:3000
Aa:3375
Ff:8875
Kk:4000

[piece roles]
big         :RrNnAaFf
major       :Rr
royal       :Kk

[piece moves]
Pp:mnW|cnF
Rr:R
Nn:N
Aa:A
Ff:F
Kk:K

[promotions]
P:F
p:f

[mandatory promotion zones]
P:XXXXXXXX/8/8/8/8/8/8/8
p:8/8/8/8/8/8/8/XXXXXXXX