title="Shatranj"
initial_position="rnafkanr/pppppppp/8/8/8/8/PPPPPPPP/RNAFKANR w"
files=8
ranks=8

[special_rules]
promotions=true

[[pieces]]
name="Pawn"
charset="Pp"
movement="mnW|cnF"
value=1000
big=false
major=false
royal=false

[[pieces]]
name="Rook"
charset="Rr"
movement="R"
value=5000
big=true
major=true
royal=false

[[pieces]]
name="Knight"
charset="Nn"
movement="N"
value=3000
big=true
major=false
royal=false

[[pieces]]
name="Alfil"
charset="Aa"
movement="A"
value=2500
big=true
major=false
royal=false

[[pieces]]
name="Ferz"
charset="Ff"
movement="F"
value=1500
big=true
major=false
royal=false

[[pieces]]
name="King"
charset="Kk"
movement="K"
value=inf
big=true
major=false
royal=true

[promotions]
P="F"
p="f"

[promotion_zones_mandatory]
P="XXXXXXXX/8/8/8/8/8/8/8"
p="8/8/8/8/8/8/8/XXXXXXXX"
