= general =
Sittuyin
8/8/4pppp/pppp4/4PPPP/PPPP4/8/8 w GK2E2H2C/gk2e2h2c

= rules =
promotions
drops
forbidden zones
setup phase

= pieces =
Pp:Feudal Lord
Ss:Feudal Lord
Gg:General
Kk:King
Cc:Chariot
Hh:Horse
Ee:Elephant

= piece values =
Pp:1000
Ss:1000
Gg:2000
Kk:4000
Cc:9000
Hh:5000
Ee:3000

= piece roles =
big         :CcHhEeGg
major       :Cc
royal       :Kk

= piece moves =
Pp:mnW|cnF
Ss:mnW|cnF
Gg:v!vF
Kk:v!vK
Cc:v!vW-*
Hh:v!vN
Ee:v!v(F|nW)

= promotions =
P:S
p:s
S:P
s:p

= mandatory promotion zones =
P:X6X/1X4X1/2X2X2/3XX3/8/8/8/8
p:8/8/8/8/3XX3/2X2X2/1X4X1/X6X
S:1XXXXXX1/X1XXXX1X/XX1XX1XX/XXX2XXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX
s:XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXX2XXX/XX1XX1XX/X1XXXX1X/1XXXXXX1

= drops =
G:def@#~S@F~psgkche|def@#-seF~?-S@sw+ne+nwF~psgkche|def@#-swF~?-S@se+ne+nwF~psgkche|def@#-nwF~?-S@ne+se+swF~psgkche|def@#-neF~?-S@nw+se+swF~psgkche
g:def@#~s@F~PSGKCHE|def@#-seF~?-s@sw+ne+nwF~PSGKCHE|def@#-swF~?-s@se+ne+nwF~PSGKCHE|def@#-nwF~?-s@ne+se+swF~PSGKCHE|def@#-neF~?-s@nw+se+swF~PSGKCHE
Pp:@#~?@#~?
Ss:@#~?@#~?
Ee:@#~?@#~?
Hh:@#~?@#~?
Cc:@#~?@#~?
Kk:@#~?@#~?

= forbidden zones =
C:XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/8
G:XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXX4/8/8
E:XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXX4/8/8
H:XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXX4/8/8
K:XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXX4/8/8
c:8/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX
g:8/8/4XXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX
e:8/8/4XXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX
h:8/8/4XXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX
k:8/8/4XXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX