= general =
Sittuyin
8/8/4pppp/pppp4/4PPPP/PPPP4/8/8 w KSSFRRNN/kssfrrnn

= rules =
promotions
promote to captured
forbidden zones
setup phase

= termination =
repetition: 3 draw
counter: 64 - draw
counting: burmese draw

= counting burmese =
RR: 8
R: 16
SS: 22
NN: 32
S: 44
default: 64

= pieces =
Pp:Feudal Lord
Ff:General
Kk:King
Rr:Chariot
Nn:Horse
Ss:Elephant

= piece order =
PFKRNSpfkrns

= piece roles =
royal       :Kk

= piece moves =
Pp:m!rnW|c!rnF|mr#-F-(mnW|dnW-u#)-sW-(meW|deW-u#)-sW-(mnW|dnW-u#)-msW|mr#-(mseF|dseF-u#)-sW-(mnW|dnW-u#)-sW-(meW|deW-u#)-sW-(mnW|dnW-u#)-msW
Ff:v!vF
Kk:v!vK
Rr:v!vW-*
Nn:v!vN
Ss:v!v(F|nW)

= promotions =
P:F
p:f

= optional promotion zones =
P:X6X/1X4X1/2X2X2/3XX3/8/8/8/8
p:8/8/8/8/3XX3/2X2X2/1X4X1/X6X

= forbidden zones =
R:XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/8
F:XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXX4/8/8
S:XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXX4/8/8
N:XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXX4/8/8
K:XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXX4/8/8
r:8/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX
f:8/8/4XXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX
s:8/8/4XXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX
n:8/8/4XXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX
k:8/8/4XXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX/XXXXXXXX
