= general =
Tjatoer
yuqxvoelkfdvxquy/rcgjbmmmmmmbjgcr/zinahstwwtshaniz/pppppppppppppppp/16/16/16/16/16/16/16/16/PPPPPPPPPPPPPPPP/ZINAHSTWWTSHANIZ/RCGJBMMMMMMBJGCR/YUQXVOELKFDVXQUY w

= rules =
promotions
halfmove clock
repetition limit

= pieces =
Aa:Archbishop
Bb:Bishop
Cc:Chariot
Dd:Duchess
Ee:Esquire
Ff:Furst
Gg:Gajah
Hh:Hawk
Ii:Imam
Jj:Jester
Kk:King
Ll:Lugal
Mm:Man
Nn:Knight
Oo:Oknha
Pp:Pawn
Qq:Queen
Rr:Rook
Ss:Shrook
Tt:Thalia
Uu:Upasaka
Vv:Viscount
Ww:Warrior
Xx:Xiphodon
Yy:Yishi
Zz:Zebra

= repetition limit =
limit:3

= halfmove clock =
limit:200
pieces:Pp

= piece order =
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz

= piece roles =
royal       :Kk

= piece moves =
Pp:mnW|imnW-{2..4}|cnF
Rr:R
Nn:N
Bb:B
Qq:Q
Kk:K
Aa:B|N
Cc:R|C
Dd:B|N|C
Ee:R|N|C
Ff:Q|N
Gg:C
Hh:N|C
Ii:R|N
Jj:B|C
Ll:Q|N|C
Mm:K|N
Oo:Q|C
Ss:W-{..4}
Tt:F-{..4}
Uu:sW|n+e+wW-{..2}|nN
Vv:F-nB
Ww:mK|cnD
Xx:W-nB
Yy:nN|sF|nF-{..2}
Zz:N-*

= promotions =
S:R
s:r
T:B
t:b
W:N
w:n
P:ZINAHRCGJBUYQ
p:zinahrcgjbuyq
M:XVOFLED
m:xvofled

= mandatory promotion zones =
P:XXXXXXXXXXXXXXXX/16/16/16/16/16/16/16/16/16/16/16/16/16/16/16
p:16/16/16/16/16/16/16/16/16/16/16/16/16/16/16/XXXXXXXXXXXXXXXX
S:XXXXXXXXXXXXXXXX/16/16/16/16/16/16/16/16/16/16/16/16/16/16/16
s:16/16/16/16/16/16/16/16/16/16/16/16/16/16/16/XXXXXXXXXXXXXXXX
T:XXXXXXXXXXXXXXXX/16/16/16/16/16/16/16/16/16/16/16/16/16/16/16
t:16/16/16/16/16/16/16/16/16/16/16/16/16/16/16/XXXXXXXXXXXXXXXX
M:XXXXXXXXXXXXXXXX/16/16/16/16/16/16/16/16/16/16/16/16/16/16/16
m:16/16/16/16/16/16/16/16/16/16/16/16/16/16/16/XXXXXXXXXXXXXXXX
W:XXXXXXXXXXXXXXXX/16/16/16/16/16/16/16/16/16/16/16/16/16/16/16
w:16/16/16/16/16/16/16/16/16/16/16/16/16/16/16/XXXXXXXXXXXXXXXX
