= general =
Xianqi
rheakaehr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RHEAKAEHR w

= rules =
promotions
forbidden zones

= pieces =
Pp:Soldier
Tt:Promoted Soldier
Cc:Cannon
Rr:Chariot
Hh:Knight
Ee:Elephant
Aa:Advisor
Kk:General

= piece values =
Pp:1000
Tt:1200
Cc:5000
Rr:5000
Hh:3000
Ee:3375
Aa:1500
Kk:2200

= piece roles =
big         :TtCcRrHhEeAaKk
major       :CcRrAa
royal       :Kk

= piece moves =
Pp:nW
Tt:n+e+wW
Cc:cdR-u#-cnR|mR
Rr:R
Hh:W-nF
Ee:F-.
Aa:F
Kk:W|kc<v!vW-{5..9}>

= promotions =
P:T
p:t

= mandatory promotion zones =
P:XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/9/9/9/9/9
p:9/9/9/9/9/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX

= forbidden zones =
K:XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX3XXX/XXX3XXX/XXX3XXX
k:XXX3XXX/XXX3XXX/XXX3XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX
A:XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX3XXX/XXX3XXX/XXX3XXX
a:XXX3XXX/XXX3XXX/XXX3XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX
E:XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/9/9/9/9/9
e:9/9/9/9/9/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX