title="Xianqi"
initial_position="rheakaehr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RHEAKAEHR w - -"
files=9
ranks=10

[special_rules]
promotions=true
forbidden_zones=true

[[pieces]]
name="Pawn"
charset="Pp"
movement="nW"
value=1000
big=false
major=false
royal=false

[[pieces]]
name="Pawn"
charset="Tt"
movement="n+e+wW"
value=1200
big=true
major=false
royal=false

[[pieces]]
name="Cannon"
charset="Cc"
movement="cdR-u#-cnR|mR"
value=5000
big=true
major=true
royal=false

[[pieces]]
name="Chariot"
charset="Rr"
movement="R"
value=5000
big=true
major=true
royal=false

[[pieces]]
name="Knight"
charset="Hh"
movement="W-nF"
value=3000
big=true
major=false
royal=false

[[pieces]]
name="Elephant"
charset="Ee"
movement="F-."
value=3375
big=true
major=false
royal=false

[[pieces]]
name="Advisor"
charset="Aa"
movement="F"
value=1500
big=true
major=true
royal=false

[[pieces]]
name="General"
charset="Kk"
movement="W|kc<v!vW-{5..9}>"
value=inf
big=true
major=false
royal=true

[promotions]
P="T"
p="t"

[promotion_zones_mandatory]
P="XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/9/9/9/9/9"
p="9/9/9/9/9/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX"

[forbidden_zones]
K = "XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX3XXX/XXX3XXX/XXX3XXX"
k = "XXX3XXX/XXX3XXX/XXX3XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX"
A = "XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXX3XXX/XXX3XXX/XXX3XXX"
a = "XXX3XXX/XXX3XXX/XXX3XXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX"
E = "XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/9/9/9/9/9"
e = "9/9/9/9/9/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX/XXXXXXXXX"